kind: pipeline
type: docker
name: test-on-amd64

platform:
  os: linux
  arch: amd64

steps:
- name: prep
  image: ubuntu:focal
  commands:
  - export DEBIAN_FRONTEND=noninteractive
  - apt-get -y update
  - apt-get -y install libboost-all-dev doxygen mkdocs graphviz zlib1g-dev gcc clang python3 python3-pip
  - pip3 install mkdocs-material

- name: buildntest
  image: ubuntu:focal
  commands:
  - mkdir build
  - cd build
  - cmake --version
  - cmake ..
  - make -j4 && ctest -V -j4
