kind: pipeline
type: docker
name: test-on-amd64

platform:
  os: linux
  arch: amd64

steps:
- name: prep
  image: ubuntu:focal
  commands:
  - export DEBIAN_FRONTEND=noninteractive
  - apt-get -y update
  - apt-get -y install libboost-all-dev doxygen mkdocs graphviz zlib1g-dev gcc clang
  - pip install mkdocs-material
  - mkdir direcc
  - touch textfile.txt

- name: buildntest
  image: ubuntu:focal
  commands:
  - ls
