kind: pipeline
type: docker
name: test-on-amd64

platform:
  os: linux
  arch: amd64

steps:
- name: prep
  image: gcc
  commands:
  - mkdir direcc
  - touch textfile.txt

- name: buildntest
  image: gcc
  commands:
  - ls
