kind: pipeline
type: docker
name: test-on-amd64

platform:
  os: linux
  arch: amd64

steps:
- name: prep
  image: gcc
  commands:
  - sudo apt install libboost-all-dev doxygen mkdocs graphviz zlib1g-dev
  - pip install mkdocs-material
  - mkdir direcc
  - touch textfile.txt

- name: buildntest
  image: gcc
  commands:
  - ls
